

#Ruta base de datos SQLite
RUTA_BD = "conf/BD_MI_EMPRESA.DB"
RUTA_CARPETA_CONF = "conf"
#Nombre de la app (por ejemplo, para ventanas o logs)
NOMBRE_APP = "P.O.S TIENDA BY PRIS"

#----------------------------------------
#Paleta de colores estilo macOS (modo claro)
#----------------------------------------
# COLOR_FONDO_PRINCIPAL = "#F2F2F7"       # Fondo general de la app
# COLOR_TARJETA_FONDO = "#FFFFFF"         # Fondo para tarjetas, contenedores
# COLOR_TEXTO_PRIMARIO = "#1C1C1E"        # Texto principal
# COLOR_TEXTO_SECUNDARIO = "#3A3A3C"      # Texto secundario, descripciones
# COLOR_BOTON_PRIMARIO = "#007AFF"        # Azul macOS para botones principales
# COLOR_BOTON_EXITO = "#34C759"           # Verde Apple para éxito o confirmación
# COLOR_BOTON_ERROR = "#FF3B30"           # Rojo Apple para errores
# COLOR_BORDE_CLARO = "#D1D1D6"           # Borde o líneas divisorias sutiles

#----------------------------------------
#Paleta de colores estilo macOS (modo oscuro)
#----------------------------------------
COLOR_FONDO_PRINCIPAL = "#1C1C1E"       # Fondo principal (negro suave)
COLOR_TARJETA_FONDO = "#2C2C2E"         # Tarjetas, modales
COLOR_TEXTO_PRIMARIO = "#FFFFFF"        # Texto principal (blanco)
COLOR_TEXTO_SECUNDARIO = "#A1A1A6"      # Texto secundario, etiquetas
COLOR_BOTON_PRIMARIO = "#0A84FF"        # Azul macOS (botones principales)
COLOR_BOTON_EXITO = "#30D158"           # Verde confirmación
COLOR_BOTON_ERROR = "#FF453A"           # Rojo error
COLOR_BORDE_CLARO = "#3A3A3C"           # Bordes, líneas sutiles

#Tabla CATEGORIA
CREATE_TABLA_CATEGORIA = '''CREATE TABLE CATEGORIA (
    CATEGORIA_ID TEXT PRIMARY KEY UNIQUE NOT NULL,
    NOMBRE       TEXT NOT NULL
);'''

INSERT_CATEGORIA = '''INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE)
                      VALUES (?, ?)'''

UPDATE_CATEGORIA = '''UPDATE CATEGORIA
                      SET NOMBRE = ?
                      WHERE CATEGORIA_ID = ?'''

DELETE_CATEGORIA = '''DELETE FROM CATEGORIA WHERE CATEGORIA_ID = ?'''

#Tabla CLIENTE
CREATE_TABLA_CLIENTE = '''CREATE TABLE CLIENTE (
    CLIENTE_ID TEXT PRIMARY KEY UNIQUE NOT NULL,
    NOMBRE     TEXT NOT NULL,
    APELLIDO TEXT NOT NULL,
    DOCUMENTO  TEXT UNIQUE,
    TELEFONO   TEXT,
    DIRECCION  TEXT
);'''

INSERT_CLIENTE = '''INSERT INTO CLIENTE (CLIENTE_ID, NOMBRE,APELLIDO, DOCUMENTO, TELEFONO, DIRECCION)
                    VALUES (?, ?, ?,?, ?, ?)'''

UPDATE_CLIENTE = '''UPDATE CLIENTE
                    SET NOMBRE = ?, APELLIDO = ?, DOCUMENTO = ?, TELEFONO = ?, DIRECCION = ?
                    WHERE CLIENTE_ID = ?'''

DELETE_CLIENTE = '''DELETE FROM CLIENTE WHERE CLIENTE_ID = ?'''


#Tabla CONFIGURACIÓN APP
CREATE_TABLA_CONFIGURACION_APP = '''CREATE TABLE CONFIG_EMPRESA (
    EMPRESA_ID TEXT PRIMARY KEY UNIQUE NOT NULL,
    NOMBRE     TEXT NOT NULL,
    DIRECCION  TEXT,
    TELEFONO   TEXT,
    MONEDA     TEXT
);'''

UPDATE_CONFIG_EMPRESA = '''UPDATE CONFIG_EMPRESA
                SET NOMBRE = ?, DIRECCION = ?, TELEFONO = ?, MONEDA = ?
                WHERE EMPRESA_ID = ?'''

INSERT_CONFIG_EMPRESA = '''INSERT INTO CONFIG_EMPRESA (EMPRESA_ID, NOMBRE, DIRECCION, TELEFONO, MONEDA)
                VALUES (?, ?, ?, ?, ?)'''

#Tabla IVA
CREATE_TABLA_IVA = '''CREATE TABLE IVA (
    IVA_ID     TEXT PRIMARY KEY UNIQUE NOT NULL,
    NOMBRE     TEXT NOT NULL,
    PORCENTAJE REAL NOT NULL
);'''

INSERT_IVA = '''INSERT INTO IVA (IVA_ID, NOMBRE, PORCENTAJE)
                VALUES (?, ?, ?)'''

UPDATE_IVA = '''UPDATE IVA
                SET NOMBRE = ?, PORCENTAJE = ?
                WHERE IVA_ID = ?'''


#Tabla PRODUCTO
CREATE_TABLA_PRODUCTO = '''CREATE TABLE PRODUCTO (
    PRODUCTO_ID  TEXT PRIMARY KEY UNIQUE NOT NULL,
    N_REFERENCIA TEXT UNIQUE,
    NOMBRE       TEXT NOT NULL,
    PRECIO       REAL NOT NULL CHECK (PRECIO >= 0),
    CATEGORIA_ID TEXT NOT NULL,
    IVA_ID       TEXT NOT NULL,
    FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA (CATEGORIA_ID),
    FOREIGN KEY (IVA_ID) REFERENCES IVA (IVA_ID)
);'''

INSERT_PRODUCTO = '''INSERT INTO PRODUCTO (PRODUCTO_ID, N_REFERENCIA, NOMBRE, PRECIO, CATEGORIA_ID, IVA_ID)
                     VALUES (?, ?, ?, ?, ?, ?)'''

UPDATE_PRODUCTO = '''UPDATE PRODUCTO
                     SET N_REFERENCIA = ?, NOMBRE = ?, PRECIO = ?, CATEGORIA_ID = ?, IVA_ID = ?
                     WHERE PRODUCTO_ID = ?'''


#Tabla VENTA
CREATE_TABLA_VENTA = '''CREATE TABLE VENTA (
    VENTA_ID           TEXT PRIMARY KEY UNIQUE NOT NULL,
    CLIENTE_ID         TEXT REFERENCES CLIENTE (CLIENTE_ID),
    TOTAL              REAL NOT NULL,
    CANTIDAD_PRODUCTOS INTEGER NOT NULL
);'''

INSERT_VENTA = '''INSERT INTO VENTA (VENTA_ID, CLIENTE_ID, TOTAL, CANTIDAD_PRODUCTOS)
                  VALUES (?, ?, ?, ?)'''

UPDATE_VENTA = '''UPDATE VENTA
                  SET CLIENTE_ID = ?, TOTAL = ?, CANTIDAD_PRODUCTOS = ?
                  WHERE VENTA_ID = ?'''


#Tabla LINEA_VENTA (relación VENTA PRODUCTO)
CREATE_TABLA_VENTA_LINEA = '''CREATE TABLE LINEA_VENTA (
    LINEA_ID        TEXT PRIMARY KEY UNIQUE NOT NULL,
    VENTA_ID        TEXT NOT NULL,
    PRODUCTO_ID     TEXT NOT NULL,
    CANTIDAD        INTEGER NOT NULL CHECK (CANTIDAD > 0),
    PRECIO_UNITARIO REAL NOT NULL CHECK (PRECIO_UNITARIO >= 0),
    IVA             REAL NOT NULL,
    TOTAL_LINEA     REAL NOT NULL,
    FOREIGN KEY (VENTA_ID) REFERENCES VENTA (VENTA_ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO (PRODUCTO_ID)
);'''

INSERT_LINEA_VENTA = '''INSERT INTO LINEA_VENTA (LINEA_ID, VENTA_ID, PRODUCTO_ID, CANTIDAD, PRECIO_UNITARIO, IVA, TOTAL_LINEA)
                        VALUES (?, ?, ?, ?, ?, ?, ?)'''

UPDATE_LINEA_VENTA = '''UPDATE LINEA_VENTA
                        SET VENTA_ID = ?, PRODUCTO_ID = ?, CANTIDAD = ?, PRECIO_UNITARIO = ?, IVA = ?, TOTAL_LINEA = ?
                        WHERE LINEA_ID = ?'''

#CREAR TABLA USUARIO
CREATE_TABLA_USUARIO = '''CREATE TABLE USUARIO (
    USUARIO_ID TEXT PRIMARY KEY UNIQUE NOT NULL,
    NOMBRE     TEXT NOT NULL,
    TRABAJADOR_NOMBRE TEXT,
    APELLIDO TEXT,
    NTELEFONO TEXT,
    CONTRASENA TEXT NOT NULL,
    ROL        TEXT NOT NULL 
);'''

INSERT_USUARIO = '''INSERT INTO USUARIO (USUARIO_ID, NOMBRE, TRABAJADOR_NOMBRE, APELLIDO, NTELEFONO, CONTRASENA, ROL)
                    VALUES (?, ?, ?, ?, ?, ?, ?)'''

UPDATE_USUARIO = '''UPDATE USUARIO
                    SET NOMBRE = ?, TRABAJADOR_NOMBRE = ?, APELLIDO = ?, NTELEFONO = ?, CONTRASENA = ?, ROL = ?
                    WHERE USUARIO_ID = ?'''

DELETE_USUARIO = '''DELETE FROM USUARIO WHERE USUARIO_ID = ?'''

