#Ruta base de datos SQLite
RUTA_BD = "/conf/BD_MI_EMPRESA.DB"
RUTA_CARPETA_CONF = "conf"
#Nombre de la app (por ejemplo, para ventanas o logs)
NOMBRE_APP = "P.O.S TIENDA BY PRIS"

#Tabla CATEGORIA
CREATE_TABLA_CATEGORIA = '''CREATE TABLE CATEGORIA (
    CATEGORIA_ID TEXT PRIMARY KEY UNIQUE NOT NULL,
    NOMBRE       TEXT NOT NULL
);'''

#Tabla CLIENTE
CREATE_TABLA_CLIENTE = '''CREATE TABLE CLIENTE (
    CLIENTE_ID TEXT PRIMARY KEY UNIQUE NOT NULL,
    NOMBRE     TEXT NOT NULL,
    DOCUMENTO  TEXT UNIQUE,
    TELEFONO   TEXT,
    DIRECCION  TEXT
);'''

#Tabla CONFIGURACIÓN APP
CREATE_TABLA_CONFIGURACION_APP = '''CREATE TABLE CONFIG_EMPRESA (
    EMPRESA_ID TEXT PRIMARY KEY UNIQUE NOT NULL,
    NOMBRE     TEXT NOT NULL,
    DIRECCION  TEXT,
    TELEFONO   TEXT,
    MONEDA     TEXT
);'''

#Tabla IVA
CREATE_TABLA_IVA = '''CREATE TABLE IVA (
    IVA_ID     TEXT PRIMARY KEY UNIQUE NOT NULL,
    NOMBRE     TEXT NOT NULL,
    PORCENTAJE REAL NOT NULL
);'''

#Tabla PRODUCTO
CREATE_TABLA_PRODUCTO = '''CREATE TABLE PRODUCTO (
    PRODUCTO_ID  TEXT PRIMARY KEY UNIQUE NOT NULL,
    N_REFERENCIA TEXT UNIQUE,
    NOMBRE       TEXT NOT NULL,
    PRECIO       REAL NOT NULL CHECK (PRECIO >= 0),
    CATEGORIA_ID TEXT NOT NULL,
    IVA_ID       TEXT NOT NULL,
    FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA (CATEGORIA_ID),
    FOREIGN KEY (IVA_ID) REFERENCES IVA (IVA_ID)
);'''

#Tabla VENTA
CREATE_TABLA_VENTA = '''CREATE TABLE VENTA (
    VENTA_ID           TEXT PRIMARY KEY UNIQUE NOT NULL,
    CLIENTE_ID         TEXT REFERENCES CLIENTE (CLIENTE_ID),
    TOTAL              REAL NOT NULL,
    CANTIDAD_PRODUCTOS INTEGER NOT NULL
);'''

#Tabla LINEA_VENTA (relación VENTA PRODUCTO)
CREATE_TABLA_VENTA_LINEA = '''CREATE TABLE LINEA_VENTA (
    LINEA_ID        TEXT PRIMARY KEY UNIQUE NOT NULL,
    VENTA_ID        TEXT NOT NULL,
    PRODUCTO_ID     TEXT NOT NULL,
    CANTIDAD        INTEGER NOT NULL CHECK (CANTIDAD > 0),
    PRECIO_UNITARIO REAL NOT NULL CHECK (PRECIO_UNITARIO >= 0),
    IVA             REAL NOT NULL,
    TOTAL_LINEA     REAL NOT NULL,
    FOREIGN KEY (VENTA_ID) REFERENCES VENTA (VENTA_ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO (PRODUCTO_ID)
);'''